apiVersion: backstage.io/v1alpha1
kind: Database
metadata:
  name: "teste"
  annotations:
    github.com/project-slug: veecode-platform/testerds
    backstage.io/techdocs-ref: dir:.
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
